analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.8031579148955643
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.690540665294975
  brandStrength: 0.1838421183638275
  rhythmicContrast: 0.256932012969628
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.2994452964048833
purpose: []
favicon: null
name: loganskees
typography_spectrum: 0.1063972527626902
